### PR TITLE
Galaan about us

### PR DESCRIPTION
**Pull request by gabdissa**
Had to quickly fix which branch I was working on. This is an updated aboutme.html from my personal branch that I am trying to merge to master.

### CODE REVIEW

**Comment by gabdissa** [comment]
Huh. I’ll check it out. When I ran my program on my local host, my code was
still there so maybe that’s because I didn’t push it.

**Comment by gabdissa** [comment]
I tried to merge my branch to master but I got an error message. I posted
the error message in our Team 34 group chat but I don't know what seems to
be the issue :(

**Comment by alisonberkowitz** [comment]
Looks like you were able to push this branch just fine, you just werent able to push your master branch, which is okay for now. @groman23 feel free to review now this looks good to go :)

**Comment by groman23** [comment]
Okay awesome! I'll review when I get home!(:

**Comment by alisonberkowitz** [comment]
Looks like Getzi's about me changes got committed to this branch by accident and merged along with it. @groman23 do you want to close out your aboutme pull request then?

**Comment by groman23** [comment]
Yeah I'll do that! I just delete it correct? Want to make sure I don't mess
anything up

Best Regards,
Getzemani Roman

**Pull request merged**
